### ISSUE TITLE
PPC: test-osuosl-ubuntu1404-ppc64_le-2 has strange linker issues

### ISSUE THREAD

**Issue by refack** [nodejs/build#1815]
https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_le-2/ has been consistently failing with a linker error:

> 11:16:01   g++-6 -o /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/mksnapshot -pthread -rdynamic -m64 -m64  -Wl,--start-group /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/mksnapshot/deps/v8/src/snapshot/embedded-file-writer.o /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/mksnapshot/deps/v8/src/snapshot/mksnapshot.o /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_base.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_init.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_libbase.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_libplatform.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_nosnapshot.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/icu/libicui18n.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_libsampler.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/icu/libicuucx.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/icu/libicudata.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/icu/libicustubdata.a /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/tools/v8_gypfiles/libv8_initializers.a -ldl -lrt -latomic -Wl,--end-group
> 11:16:04 /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/v8_base/deps/v8/src/bootstrapper.o:(.toc1+0x218): undefined reference to `v8::internal::StatisticsExtension::kSource'
> 11:16:04 /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/v8_base/deps/v8/src/bootstrapper.o:(.toc1+0x228): undefined reference to `vtable for v8::internal::StatisticsExtension'
```

I marked it offline for the time being.

![image](https://user-images.githubusercontent.com/96947/58643172-c6195900-82cc-11e9-8889-81f2e541e0ee.png)

**Comment by mhdawson** [comment]
I've pinged @sam-github to make sure this is on his radar.  We were both out last week at the Collab summit.

**Comment by sam-github** [comment]
@miladfarca, you looked at this a bit? Did you have any ideas, or even manage to reproduce this?

**Comment by refack** [comment]
I believe @sam-github has resolved this, or at least it was resolved by other means.

We now have a different but intermittent problem:

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23617/console
```
08:32:35 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
08:32:35   ---
08:32:35   duration_ms: 0.166
08:32:35   ...
08:42:35 Build timed out (after 10 minutes). Marking the build as failed.
08:42:35 gmake[1]: *** [test-ci] Terminated
```

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23618/console
```
09:35:15 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
09:35:15   ---
09:35:15   duration_ms: 0.176
09:35:15   ...
09:45:15 Build timed out (after 10 minutes). Marking the build as failed.
09:45:15 gmake[1]: *** [test-ci] Terminated
```

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23622/console
```
11:38:22 ok 2539 message/vm_dont_display_syntax_error
11:38:22   ---
11:38:22   duration_ms: 0.110
11:38:22   ...
11:48:22 Build timed out (after 10 minutes). Marking the build as failed.
11:48:23 gmake[1]: *** [test-ci] Terminated
```

easy to reproduce:
```bash
> su iojs
> cd /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64
> NODE_NAME=test-osuosl-aix61-ppc64_be-3
> python tools/test.py --report pseudo-tty
```
or
```
python -m trace -t tools/test.py --report pseudo-tty
```
to see a trace of all lines. Seems like there's an issue with sub-process spawning and ptty, since the process stalls on:
```
test.py(648):   if faketty:
test.py(649):     os.close(rest['stdout'])
```
where [`rest['stdout']`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L648-L649) is `fd_out` created by [`(out_master, fd_out) = pty.openpty()`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L721-L723)

**Comment by richardlau** [comment]
> 
> 
> I believe @sam-github has resolved this, or at least it was resolved by other means.
> 
> We now have a different but intermittent problem:
> 
> https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23617/console
> 
> ```
> 08:32:35 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
> 08:32:35   ---
> 08:32:35   duration_ms: 0.166
> 08:32:35   ...
> 08:42:35 Build timed out (after 10 minutes). Marking the build as failed.
> 08:42:35 gmake[1]: *** [test-ci] Terminated
> ```
> 
> https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23618/console
> 
> ```
> 09:35:15 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
> 09:35:15   ---
> 09:35:15   duration_ms: 0.176
> 09:35:15   ...
> 09:45:15 Build timed out (after 10 minutes). Marking the build as failed.
> 09:45:15 gmake[1]: *** [test-ci] Terminated
> ```
> 
> https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23622/console
> 
> ```
> 11:38:22 ok 2539 message/vm_dont_display_syntax_error
> 11:38:22   ---
> 11:38:22   duration_ms: 0.110
> 11:38:22   ...
> 11:48:22 Build timed out (after 10 minutes). Marking the build as failed.
> 11:48:23 gmake[1]: *** [test-ci] Terminated
> ```
> 
> easy to reproduce:
> 
> ```shell
> > su iojs
> > cd /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64
> > NODE_NAME=test-osuosl-aix61-ppc64_be-3
> > python tools/test.py --report pseudo-tty
> ```
> 
> or
> 
> ```
> python -m trace -t tools/test.py --report pseudo-tty
> ```
> 
> to see a trace of all lines. Seems like there's an issue with sub-process spawning and ptty, since the process stalls on:
> 
> ```
> test.py(648):   if faketty:
> test.py(649):     os.close(rest['stdout'])
> ```
> 
> where [`rest['stdout']`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L648-L649) is `fd_out` created by [`(out_master, fd_out) = pty.openpty()`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L721-L723)

Those are on AIX though (the original post was Linux on PPC LE).

**Comment by miladfarca** [comment]
@sam-github this is a separate issue I assume, the one I was looking at was related to the `/test-worker-prof.js` test case.

**Comment by refack** [comment]
> Those are on AIX though (the original post was Linux on PPC LE).

Yep, I'm not sure why I read the title wrong. Spun off https://github.com/nodejs/build/issues/1820.

**Comment by sam-github** [comment]
The history here is a bit confusing, because multiple issues are discussed. I hid @refack and @richardlau comments above that are related to #1820, just to make this easier to read.

@miladfarca, we have discussed this linker error before, in slack:

```
16:06:17   g++ -o /home/iojs/build/workspace/node-test-commit-plinux/nodes/centos7-ppcle/out/Release/obj.target/v8_base/deps/v8/src/extensions/statistics-extension.o ../deps/v8/src/extensions/statistics-extension.cc '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_PPC' '-DV8_TARGET_ARCH_PPC64' '-
Milad Farazmand  12 days ago
The build that's failing isn't compiling this file, hence a missing symbol error, now look into why this file is not included when you are compiling your code (edited)
SAM ROBERTS  12 days ago
interesting. and odd :disappointed:. thanks for looking.
Milad Farazmand  12 days ago
no issues,  might be helpful to look into tools/v8_gypfiles/v8.gyp, every machine specific file that needs to be compiled for v8 is listed there
```

Luckily (?) the linker problems stopped over the weekend, and my build passed and was merged (by someone else): https://github.com/nodejs/node/pull/27834

But, there seems to be a real issue.

Reviewing https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_le-2/builds, many failed with linker errors (though some with pty timeouts, as in #1820).
- https://ci.nodejs.org/job/node-test-commit-plinux/nodes=ppcle-ubuntu1404/26123/console: undefined reference to `vtable for v8::internal::StatisticsExtension'
- https://ci.nodejs.org/job/node-test-commit-plinux/nodes=ppcle-ubuntu1404/26122/console: ditto
-  https://ci.nodejs.org/job/node-test-commit-plinux/nodes=ppcle-ubuntu1404/26119/console
- ... etc

I'll go look at the .gyp file that Milad mentions in the workspace, and compare it to a clean build. Since the workers is offline, I should be able to redo the build in the workspace from ssh, and see if it fails to link for me, too.

**Comment by miladfarca** [comment]
`v8::internal::StatisticsExtension::kSource` is defined in `statistics-extension.cc` under V8. Looking at the latest job under this machines (hash cfbb5bb) on May 30, the `statistics-extension` object file is not compiled properly, this is the output of `nm`:

```
$ nm out/Release/obj.target/v8_base/deps/v8/src/extensions/statistics-extension.o

nm: out/Release/obj.target/v8_base/deps/v8/src/extensions/statistics-extension.o: File truncated
```
I copied the directory, re configured and compiled it from scratch and it worked fine. Seems like jenkins was interrupted mid compilation and the truncated `statistics-extension.o` was used in the later test jobs and commits?

Are we clearing cache/workspace properly? 
Is it possible to clear the workspace manually and activate the machine and see if it happens again.

**Comment by sam-github** [comment]
Its possible the workspace isn't cleared, but its also possible that a bad build got ccached, which would cause the issue to come back over and over.

I removed the .o file, cleared the ccache, and reenabled the machine.

    iojs@test-osuosl-ubuntu1404-ppc64--le-2:~/build/workspace$ rm ./node-test-commit-plinux/nodes/ppcle-ubuntu1404/out/Release/obj.target/v8_base/deps/v8/src/extensions/statistics-extension.o

**Comment by sam-github** [comment]
I just got a green build from the daily: https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_le-2/builds

Perhaps this issue is resolved?

**Comment by sam-github** [comment]
https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_le-2/builds looks resolved, closing this.
